### PR TITLE
Updates and cross-build for Scala.js, Scala Native

### PR DESCRIPTION
**Pull request by armanbilge**
This was is a pure cross! Tests passing on JVM and JS. Just build reconfiguring, sorry about that.

### CODE REVIEW

**Comment by armanbilge** [comment]
Polite bump :) I think this one will help port coulomb/lucuma-core to Scala 3 actually. Thanks!

**Comment by jf-botto** [comment]
@armanbilge we may need this to compile Grackle core :)

**Comment by armanbilge** [comment]
@jbotto94 Ah right, I forgot about this one 😂

**Comment by nkgm** [comment]
Gentle nudge 😅

**Comment by tpolecat** [comment]
@armanbilge build failure here. I'll add you as a maintainer and you can merge/publish once it's working

**Comment by armanbilge** [comment]
Thanks Rob!

**Pull request merged**
